apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-trainer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-trainer
  template:
    metadata:
      labels:
        app: java-trainer
    spec:
      containers:
      - name: java-trainer
        image: melnikprod/java-trainer:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: java-trainer-service
spec:
  selector:
    app: java-trainer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: java-trainer-statefulset
spec:
  serviceName: "java-trainer-service"
  replicas: 3
  selector:
    matchLabels:
      app: java-trainer
  template:
    metadata:
      labels:
        app: java-trainer
    spec:
      containers:
      - name: java-trainer
        image: melnikprod/java-trainer:latest
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-claim
  volumeClaimTemplates:
  - metadata:
      name: data-claim
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi