name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: my-project-id
  DOCKER_REGISTRY: gcr.io
  K8S_NAMESPACE: default
  K8S_CLUSTER: my-cluster
  SERVICES: "java-announcement,java-battle,java-pokedex,java-testing,java-trainer"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [java-announcement, java-battle, java-pokedex, java-testing, java-trainer]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode | \
          gcloud auth activate-service-account --key-file=-
          gcloud auth configure-docker

      - name: Check for changes in each service directory
        id: check-changes
        run: |
          changed_dirs=()
          for service in $(echo ${{ env.SERVICES }} | tr ',' ' '); do
            if [[ $(git diff --name-only HEAD^ HEAD -- $service) ]]; then
              changed_dirs+=($service)
            fi
          done
          echo "::set-output name=changed_dirs::${changed_dirs[@]}"

      - name: Build and push Docker image
        if: contains(steps.check-changes.outputs.changed_dirs, ${{ matrix.service }})
        run: |
          docker build -t $DOCKER_REGISTRY/$PROJECT_ID/${{ matrix.service }}:$GITHUB_SHA .
          docker push $DOCKER_REGISTRY/$PROJECT_ID/${{ matrix.service }}:$GITHUB_SHA

      - name: Update Kubernetes deployment
        if: contains(steps.check-changes.outputs.changed_dirs, ${{ matrix.service }})
        uses: google-github-actions/update-k8s-deployment@v0.4
        with:
          name: ${{ matrix.service }}
          image: $DOCKER_REGISTRY/$PROJECT_ID/${{ matrix.service }}:$GITHUB_SHA
          namespace: $K8S_NAMESPACE
          cluster: $K8S_CLUSTER

      - name: Verify deployment
        if: contains(steps.check-changes.outputs.changed_dirs, ${{ matrix.service }})
        run: |
          kubectl rollout status deployment/${{ matrix.service }} -n $K8S_NAMESPACE
