name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  K8S_NAMESPACE: java-test
  GKE_PROJECT_ID: testgke-378818
  GKE_CLUSTER: gke-test    # Add your cluster name here.
  GKE_ZONE: us-east1-a   # Add your cluster zone here.
  SERVICES: "java-announcement,java-battle,java-pokedex,java-testing,java-trainer"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [java-announcement, java-battle, java-pokedex, java-testing, java-trainer]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.0
        with:
          project_id: ${{ env.GKE_PROJECT_ID }}
          skip_install: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Check for changes in each service directory
        id: check-changes
        run: |
          changed_dirs=()
          for service in $(echo ${{ env.SERVICES }} | tr ',' ' '); do
            if [[ $(git diff --name-only HEAD^ HEAD -- $service) ]]; then
              changed_dirs+=($service)
            fi
          done
          echo "::set-output name=changed_dirs::${changed_dirs[@]}"

      - name: Build and push Docker image
        if: contains(steps.check-changes.outputs.changed_dirs, ${{ matrix.service }})
        run: |
          docker build -t $DOCKER_REGISTRY/$GKE_PROJECT_ID/${{ matrix.service }}:$GITHUB_SHA .
          docker tag $DOCKER_REGISTRY/$GKE_PROJECT_ID/${{ matrix.service }}:$GITHUB_SHA $DOCKER_REGISTRY/$GKE_PROJECT_ID/${{ matrix.service }}:latest
          docker push $DOCKER_REGISTRY/$GKE_PROJECT_ID/${{ matrix.service }}:$GITHUB_SHA
          docker push $DOCKER_REGISTRY/$GKE_PROJECT_ID/${{ matrix.service }}:latest

      - name: Authenticate with GKE
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Kubernetes
        if: contains(steps.check-changes.outputs.changed_dirs, ${{ matrix.service }})
        run: |
          envsubst < ./${{ matrix.service }}/k8s/${{ matrix.service }}.yml | kubectl apply -f -

      - name: Verify deployment
        if: contains(steps.check-changes.outputs.changed_dirs, ${{ matrix.service }})
        run: |
          kubectl rollout status deployment/${{ matrix.service }} -n $K8S_NAMESPACE
